name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.7

      - name: Run Tests Client
        run: go test -cover ./...
        working-directory: ./client

      - name: Run Tests Service
        run: go test -cover ./...
        working-directory: ./service

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Run Lints Client
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
          working-directory: ./client

      - name: Run Lints Service
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
          working-directory: ./service
